#!/bin/bash

function usage {
	echo ' _________________________________ '
	echo '|                                 |'
	echo '| Uso: api_create_installer	    |'
	echo '| Ejemplo: api_create_installer	|'
	echo '|_________________________________|'
	echo '					                    				'
}

set -e

if [ $# -ne 0 ] ; then
	usage
	exit 1
fi

mkdir $HOME/.apitools
cp -rf $(pwd)/* $HOME/.apitools/
echo 'export PATH="$PATH:$HOME/.apitools"' >> ~/.bashrc

